### ISSUE TITLE
Rename to prism

### ISSUE THREAD

**Issue by jml** [weaveworks/prism#28]
- [x] Rename the GitHub repository
- [x] Update code to use "prism" package, not "frankenstein"
- [x] Update prometheus branch to use "prism" package
- [x] Update code  to use "prism", not "frank"
- [x] Revise README to ensure naming makes sense
- [x] Create new repository on Docker Hub
- [x] Update CI to work with new names
- [x] Update deployment config for new image names
- [x] Roll out new image names
   - [x] to dev
   - [x] to prod
- [x] Update prism to depend on prometheus branch w/ prism rename
- [x] Update the feature flag
   - [x] UI code
   - [x] database (probably need 2 updates to UI code for smooth migration)
- [x] Update the production dashboards
- [x] Update playbook

**Comment by jml** [comment]
While testing on Weave Cloud, I saw: 

```
error reading base template: Asset web/ui/templates/_prism_base.html not found
```

**Comment by juliusv** [comment]
Ah! You'll need to `make assets`.

**Comment by juliusv** [comment]
(in the Prometheus fork, that is)

**Comment by jml** [comment]
Thanks @juliusv, that saved me a lot of time! Just posted https://github.com/tomwilkie/prometheus/pull/79 which does what you suggest.
