### ISSUE TITLE
Ingesters log too much

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/prism#36]
9m log entries in 8hrs, which is about 40% of the clusters output (another 40% being kube-dns, which is now fixed).

66% of the logs lines from the ingester are “Flushing chunk".

**Comment by tomwilkie** [comment]
<img width="765" alt="screen shot 2016-09-29 at 10 21 48" src="https://cloud.githubusercontent.com/assets/444037/18964712/f1429094-862e-11e6-805a-1341a2dba73b.png">
<img width="396" alt="screen shot 2016-09-29 at 10 23 39" src="https://cloud.githubusercontent.com/assets/444037/18964713/f15a4f36-862e-11e6-8daa-1d40e6cb7e4a.png">

**Comment by tomwilkie** [comment]
- “Flushing” occurs 9,126,042 times of 18,512,409 log lines.
- 2,040,808 log lines don’t include include POST or Flushing: https://weave.loggly.com/search#terms=-Flushing%20-POST&from=2016-09-28T17%3A27%3A56.901Z&until=2016-09-29T17%3A27%3A56.901Z&source_group=&filter=json.kubernetes.namespace_name%3Bprism
  - Generally its "Got update to ring” and "Heartbeating to consul…"

**Comment by juliusv** [comment]
I'd say kill the logs for these things, use metrics instead! (except for errors and their exact messages)

**Comment by jml** [comment]
I was going to fix the "Flushing" one as part of #37, but it's actually from prism.go in our prometheus fork. I don't know what the state of that is (@juliusv says it's going away), but it's a one line fix, so I've filed tomwilkie/prometheus#82

**Comment by jml** [comment]
Probably fixed by https://github.com/weaveworks/prism/pull/46. Please re-open if not.

**Comment by jml** [comment]
Now getting cycles of these:

```
time="2016-10-18T16:13:23Z" level=info msg="Done flushing chunks." source="ingester.go:409"
time="2016-10-18T16:14:22Z" level=info msg="Flushing chunks... (exiting: false)" source="ingester.go:386"
time="2016-10-18T16:14:22Z" level=info msg="Flushing user 2..." source="ingester.go:412"
time="2016-10-18T16:14:22Z" level=info msg="Flushing user 1..." source="ingester.go:412"
time="2016-10-18T16:14:23Z" level=info msg="Done flushing user 1." source="ingester.go:433"
time="2016-10-18T16:14:23Z" level=info msg="Done flushing user 2." source="ingester.go:433"
```

I haven't yet looked up what they signify.
