### ISSUE TITLE
Frankenstein needs to accept gRPC

### ISSUE THREAD

**Issue by jml** [weaveworks/prism#6]
*From @tomwilkie*

*Copied from original issue: tomwilkie/frankenstein#5*

**Comment by jml** [comment]
*From @jml*

@tomwilkie Why?

**Comment by jml** [comment]
*From @tomwilkie*

Upstream has gone with gRPC for the generic write path, we want people to use vanilla prometheus for their retrievers:

prometheus/prometheus#1930

**Comment by jml** [comment]
*From @tomwilkie*

See prometheus/prometheus#1957

**Comment by jml** [comment]
See also weaveworks/service#832

**Comment by jml** [comment]
Using gRPC is really tricky. We're looking into other options.

**Comment by juliusv** [comment]
Upstream was switched back to HTTP+protobuf. Closing this.
